`timescale 1ns/1ps

// tb_commit_log.sv
//
// Loads a random program from program.hex (one hex-encoded instruction
// word per line, exactly what $readmemh expects -- generated by
// gen_program.py), runs it, and emits a per-instruction commit log to
// commit_log.txt for comparison against Spike's --log-commits trace.
//
// Log format (one or more lines per retiring instruction):
//   PC  <idx> <pc_hex>
//   REG <idx> <rd_decimal> <value_hex>     (only if the instruction writes a register)
//   MEM <idx> <addr_hex> <value_hex>       (only if the instruction writes memory)
//
// <idx> is a shared retirement index correlating these lines: MEM lines are
// captured one pipeline stage (one cycle) earlier than PC/REG lines for the
// same instruction, because this core commits memory writes in the MEM
// stage and register writes in WB. The EX/MEM -> MEM/WB pipeline registers
// advance unconditionally every cycle (no stall/flush ever gates that
// specific transfer in this design -- confirmed from the RTL: neither
// always_ff block has a flush/stall branch, only reset), so a counter
// incremented once per ex_mem_r.valid cycle and a second counter
// incremented once per mem_wb_r.valid cycle stay in lockstep, offset by
// exactly one cycle -- giving MEM lines and their corresponding PC/REG
// lines matching <idx> values without needing any new DUT-side signal.
//
// The generated program is expected to end in a deliberate infinite
// self-branch (beq x0,x0,0) rather than relying on any host/target
// interface exit convention -- this testbench simply runs for a fixed,
// generous retirement budget (MAX_RETIRE) and dumps whatever's happened by
// then, mirroring how the Python side detects "done" by watching for the
// PC value to stop changing.

module tb_commit_log();

    localparam MAX_RETIRE = 20000;

    logic clk, rst_n;
    logic [31:0] pc_out;

    riscv_core dut (
        .clk(clk),
        .rst_n(rst_n),
        .pc_out(pc_out)
    );

    initial begin
        clk = 1'b0;
        forever #10 clk = ~clk;
    end

    // Hard backstop in case something hangs entirely (distinct from the
    // MAX_RETIRE-based natural stop below).
    initial begin
        #4000000;
        $display("tb_commit_log: hard timeout reached, forcing exit");
        $finish;
    end

    task reset_core();
        begin
            rst_n = 1'b0;
            @(negedge clk);
            rst_n = 1'b1;
        end
    endtask

    integer log_fd;
    integer mem_commit_idx;
    integer wb_commit_idx;
    logic   logging_active;

    initial begin
        mem_commit_idx = 0;
        wb_commit_idx  = 0;
        logging_active = 1'b0;
    end

    always @(posedge clk) begin
        if (rst_n && logging_active) begin
            if (dut.ex_mem_r.valid) begin
                if (dut.ex_mem_r.mem_write)
                    $fdisplay(log_fd, "MEM %0d %h %h", mem_commit_idx, dut.ex_mem_r.alu_result, dut.ex_mem_r.store_data);
                mem_commit_idx <= mem_commit_idx + 1;
            end

            if (dut.mem_wb_r.valid) begin
                $fdisplay(log_fd, "PC %0d %h", wb_commit_idx, dut.mem_wb_r.pc);
                if (dut.mem_wb_r.reg_write)
                    $fdisplay(log_fd, "REG %0d %0d %h", wb_commit_idx, dut.mem_wb_r.rd_addr, dut.wb_write_data);
                wb_commit_idx <= wb_commit_idx + 1;
            end
        end
    end

    initial begin
        for (int j = 0; j < 1024; j++) dut.u_instruction_mem.mem[j] = 32'h00000013;
        // data_mem.sv's ram[] has no reset -- Icarus (correctly) shows 'x' for any
        // word never written by a prior store. A random program that loads before
        // it stores to a given address will hit this. Zero-initializing here
        // matches the standard convention a reference model would use, so a
        // load-before-store isn't a false mismatch caused by initialization
        // convention rather than an actual functional difference.
        for (int j = 0; j < 1024; j++) dut.u_data_mem.ram[j] = 32'h00000000;
        $readmemh("program.hex", dut.u_instruction_mem.mem);

        log_fd = $fopen("commit_log.txt", "w");
        if (log_fd == 0) begin
            $display("ERROR: could not open commit_log.txt for writing");
            $finish;
        end

        reset_core();
        logging_active = 1'b1;

        // Run until MAX_RETIRE instructions have reached WB. Since the
        // generated program always ends in an infinite self-branch, this
        // will always eventually hit MAX_RETIRE rather than running
        // forever -- there is no other natural "done" condition to detect
        // here (unlike the earlier fixed-program testbenches, which could
        // wait for pc_out to exceed a known program length).
        while (wb_commit_idx < MAX_RETIRE) begin
            @(posedge clk);
        end

        // Cleared before $fclose, and read by the always block above every
        // cycle -- bounds the logging block to at most one extra (harmless,
        // still-valid-fd) firing on the crossing edge itself, rather than
        // relying on exact same-edge NBA-region timing to avoid a write
        // after the file is closed.
        logging_active = 1'b0;
        $fclose(log_fd);
        $display("tb_commit_log: done, %0d instructions retired, log written to commit_log.txt", wb_commit_idx);
        $finish;
    end

endmodule